# Generated by Django 2.0.13 on 2019-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
